[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:backend]
directory=/app
command=python -m uvicorn backend.server:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
startretries=10
startsecs=1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:frontend]
directory=/app
command=streamlit run src/main.py --server.address=0.0.0.0 --server.port=8501
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
startretries=10
startsecs=1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0